spring.application.name=api
server.port=8085
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/dreamspace_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Troiza007
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true

# ???????????? ????????????? ??????? ???????? (data.sql)
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# JWT Configuration
jwt.secret=pY5&bN2#sbU0%xvI7*tzRcuK1_zoQ9NE
jwt.expiration=86400000

spring.jpa.hibernate.ddl-auto=update